services:
  pufferpanel:
    image: pufferpanel/pufferpanel:latest
    container_name: pufferpanel
    restart: on-failure
    ports:
      - "8080:8080"
      - "5657:5657"
    volumes:
      - pufferpanel-config:/etc/pufferpanel
      - pufferpanel-data:/var/lib/pufferpanel:z
      - /var/run/docker.sock:/var/run/docker.sock
    # environment:
    #   - PUFFERPANEL_WEB_HOST=0.0.0.0

volumes:
  pufferpanel-config:
  pufferpanel-data:
