services:
  voyagers:
    image: "ghcr.io/lancehampton/voyagers-of-nera-docker:latest"
    depends_on:
      - voyagers-tailscale
    network_mode: "service:voyagers-tailscale"
    restart: unless-stopped
    container_name: voyagers-server
    volumes:
      - "./gamedata:/gamedata"
      - "./saved:/saved"
      - "./config:/config"
    # ports:
    #   - "0.0.0.0:7777:7777/udp"  # game port
    #   - "0.0.0.0:7778:27015/udp" # steam query port

  voyagers-tailscale:
    image: tailscale/tailscale:latest
    container_name: voyagers-tailscale
    hostname: voyagers
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /var/lib/tailscale/palworld:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    networks:
      - voyagers_nw
    ports:
      - "7777:7777/udp"
      - "27015:27015/udp"
networks:
  voyagers_nw:
    name: voyagers_nw