services:
  whatsupdocker:
    image: getwud/wud:8.1
    container_name: wud
    restart: unless-stopped
    ports:
      - 3090:3000
    env_file: .env
    environment:
      - WUD_WATCHER_APPS_SOCKET=/var/run/docker.sock