services:
  whatsupdocker:
    image: getwud/wud:8.1
    container_name: wud
    environment:
      - WUD_REGISTRY_CUSTOM_CODEBERG_URL=https://codeberg.org/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3090:3000