---
# url: https://proxmox.host.or.ip:8006
# token: username@pam!Token ID
# secret: secret

url: {{HOMEPAGE_VAR_PROXMOX_HOST}}
token: {{HOMEPAGE_VAR_PROXMOX_TOKEN}}
secret: {{HOMEPAGE_VAR_PROXMOX_SECRET}}
