---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
# For icons, please see:
# https://gethomepage.dev/configs/services/#icons

- Hypervisor:
    - Thor:
        icon: proxmox.png # icons found here https://github.com/walkxcode/dashboard-icons
        href: {{HOMEPAGE_VAR_PROXMOX_URL}}
        description: Proxmox VE Node
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PROXMOX_HOST}}
            username: {{HOMEPAGE_VAR_PROXMOX_TOKEN}}
            password: {{HOMEPAGE_VAR_PROXMOX_SECRET}}
            node: thor # optional
    - Home Assistant:
        icon: home-assistant.png
        href: {{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}
        description: HAOS VM
        proxmoxNode: thor
        proxmoxVMID: 100
        proxmoxType: qemu # This is the default, so it can be omitted
        # showStats: true

- External Services:
    - Birdnet:
        icon: birdnet.png
        href: {{HOMEPAGE_VAR_BIRDNET_URL}}
        description: Container Status
        server: local-docker
        container: birdnet-go
    - Rallly:
        icon: rallly.png
        href: http://localhost/
        description: TODO

- Internal Services:
    - Komodo:
        icon: komodo
        href: {{HOMEPAGE_VAR_KOMODO_URL}}
        description: Stack Stats
        # server: local-docker
        # container: komodo-core-1
        widget:
            type: komodo
            url: {{HOMEPAGE_VAR_KOMODO_URL}}
            key: {{HOMEPAGE_VAR_KOMODO_KEY}}
            secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
            # showSummary: true # optional, default: false
            showStacks: true # optional, default: false
            fields: ["total", "running", "down", "unhealthy"]
    - Uptime Kuma: # https://gethomepage.dev/widgets/services/uptime-kuma/
        href: http://localhost/
        description: TODO
