---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
# For icons, please see:
# https://gethomepage.dev/configs/services/#icons

- Hypervisor:
    - Proxmox:
        icon: proxmox.png # icons found here https://github.com/walkxcode/dashboard-icons
        href: {{HOMEPAGE_VAR_PROXMOX_URL}}
        description: Thor PVE Stats
        widget:
            type: proxmox
            url: {{HOMEPAGE_VAR_PROXMOX_HOST}}
            username: {{HOMEPAGE_VAR_PROXMOX_TOKEN}}
            password: {{HOMEPAGE_VAR_PROXMOX_SECRET}}
            node: thor # optional
    - Beszel:
        icon: beszel
        href: {{HOMEPAGE_VAR_BESZEL_URL}}
        description: Thor Beszel Stats
        # server: local-docker
        # container: beszel
        widget:
            type: beszel
            url: {{HOMEPAGE_VAR_BESZEL_URL}}
            username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
            password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}}
            systemId: {{HOMEPAGE_VAR_BESZEL_SYSTEM_ID}}
            version: 2 # optional, default is 1
            fields: ["cpu", "memory", "disk", "network"]
    - Home Assistant:
        icon: home-assistant
        href: {{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}
        description: HAOS VM
        proxmoxNode: thor
        proxmoxVMID: 100
        proxmoxType: qemu # This is the default, so it can be omitted
        # showStats: true

- External Services:
    - Birdnet:
        icon: birdnet
        href: {{HOMEPAGE_VAR_BIRDNET_URL}}
        description: Container Status
        server: local-docker
        container: birdnet-go
    - Rallly:
        icon: rallly
        href: http://localhost/
        description: TODO

- Internal Services:
    - Komodo:
        icon: komodo
        href: {{HOMEPAGE_VAR_KOMODO_URL}}
        description: Stack Stats
        server: local-docker
        container: komodo-core-1
        widget:
            type: komodo
            url: {{HOMEPAGE_VAR_KOMODO_URL}}
            key: {{HOMEPAGE_VAR_KOMODO_KEY}}
            secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
            # showSummary: true # optional, default: false
            showStacks: true # optional, default: false
            fields: ["total", "running", "down", "unhealthy"]
    - Readeck:
        icon: readeck.png
        href: {{HOMEPAGE_VAR_READECK_URL}}
        description: Read-It-Later
        server: local-docker
        container: readeck
    # - What's Up Docker:
    #     icon: whats-up-docker.png
    #     href: {{HOMEPAGE_VAR_WUD_URL}}
    #     description: Image Updates
    #     server: local-docker
    #     container: wud
    #     widget:
    #         type: whatsupdocker
    #         url: {{HOMEPAGE_VAR_WUD_URL}}
    #         username: {{HOMEPAGE_VAR_WUD_USERNAME}}
    #         password: {{HOMEPAGE_VAR_WUD_PASSWORD}}
