services:
  panel:
    image: ghcr.io/pelican-dev/panel:latest
    restart: always
    networks:
      - default
    ports:
      - "9080:80"
      - "9443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - pelican-data:/pelican-data
      - pelican-logs:/var/www/html/storage/logs
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: "${APP_URL:-http://localhost}"
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      XDG_DATA_HOME: /pelican-data

volumes:
  pelican-data:
  pelican-logs:

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16