server:
  assets-path: /app/assets

branding:
  logo-url: &logo_url https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Valknut-Symbol-triquetra.svg/540px-Valknut-Symbol-triquetra.svg.png
  favicon-url: *logo_url
  app-icon-url: *logo_url

theme:
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  # custom-css-file: /assets/user.css
  disable-picker: false

  # Default theme (gruvbox-dark)
  background-color: 0 0 16
  primary-color: 43 59 81
  positive-color: 61 66 44
  negative-color: 6 96 59

  presets:
    teal-city:
      background-color: 225 14 15
      primary-color: 157 47 65
      contrast-multiplier: 1.1

    # kanagawa-dark:
    #   background-color: 240 13 14
    #   primary-color: 51 33 68
    #   negative-color: 358 100 68
    #   contrast-multiplier: 1.2

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: home.yml
  - $include: gaming.yml
#  - $include: work.yml